default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  url: <%= ENV["DATABASE_URL"].presence || "postgres://localhost/bookkeeper_agent_development" %>

development:
  <<: *default

test:
  <<: *default
  url: <%= ENV["DATABASE_URL"].presence || "postgres://localhost/bookkeeper_agent_test" %>

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") %>
