source "https://rubygems.org"

ruby "3.3.0"

gem "rails", "~> 8.0.0"
gem "pg", "~> 1.5"
gem "puma", "~> 6.4"
gem "graphql", "~> 2.3"
gem "omniauth", "~> 2.1"
gem "omniauth-openid-connect", "~> 0.8"
gem "pundit", "~> 2.3"
gem "faraday", "~> 2.11"
gem "json_schemer", "~> 2.2"
gem "image_processing", "~> 1.13"
gem "ruby-vips", "~> 2.2"
gem "solid_queue", "~> 1.1"
gem "mission_control-jobs", "~> 1.1"
gem "aws-sdk-s3", "~> 1.153"
gem "sentry-ruby", "~> 5.19"
gem "sentry-rails", "~> 5.19"
gem "opentelemetry-sdk", "~> 1.5"
gem "opentelemetry-exporter-otlp", "~> 0.29"

group :development, :test do
  gem "rspec-rails", "~> 7.0"
  gem "factory_bot_rails", "~> 6.4"
  gem "rubocop", require: false
  gem "rubocop-rails-omakase", require: false
end

